### ISSUE TITLE
run GCN on my own dataset

### ISSUE THREAD

**Issue by samahwaleed** [andrejmiscic/gcn-pytorch#1]
Hi there is on things I want to ask . It can be a dumb question as I am new to it.

I want to run GCN on my own image dataset. Other people build a graph using faster rcnn output for objects detection purpose.
My question is how we can build a graph using yolo output?.

Thanks

**Comment by andrejmiscic** [comment]
Hi!

The simplest way would be to treat each object detected by YOLO as a separate node and construct a complete graph. To initialize node features you can use the image features of detected objects. 
Additionally, you could use some more complex linking, e.g. based on distances between object positions in the image or even based on objects themselves (e.g. a tire and a car should probably be connected).

Anyhow, I think that this repo won't suffice for any processing of the constructed graphs as it is just a simple reimplementation of original GCN paper. You can take a look at [PyTorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/) which is a more complete library for graph neural networks built upon PyTorch.

**Comment by samahwaleed** [comment]
ok, Thank you.
